Fix typo
OpenShelter/fastlane-plugin-rome pull request #14
Opened 2019-08-03 07:28 UTC by tedgonzalez

2019-08-05 19:25 UTC, tmspzz requested changes

2019-08-05 19:25 UTC, tmspzz commented on lib/fastlane/plugin/rome/actions/rome_action.rb
> +          cmd << "--missing" if params[:present] == true
This should probably  `--present`

2019-08-05 19:26 UTC, tmspzz commented
@tedgonzalez thanks for your contribution! I left a comment, I think you made a copy/paste oversight

2019-08-06 08:53 UTC, tedgonzalez commented on lib/fastlane/plugin/rome/actions/rome_action.rb
> +          cmd << "--missing" if params[:present] == true
Sorry about that, fixed!

2019-08-06 09:09 UTC, tmspzz approved these changes

2019-08-06 09:09 UTC, merged